services:
  mongo_db:
    image: mongo:latest
    container_name: library_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: book-cache
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: library_api
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo_admin:password@mongo_db:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo_db
      - redis

  prism:
    image: stoplight/prism:4
    container_name: library_prism_mock
    ports:
      - "4010:4010"
    volumes:
      - ./openapi.yaml:/etc/prism/openapi.yaml:ro
    command: mock -h 0.0.0.0 /etc/prism/openapi.yaml

  locust:
    image: locustio/locust:latest
    container_name: library_locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --host=http://app:8000
    depends_on:
      - app

volumes:
  mongo_data: